---
#-----------------------------------
# Hub
#-----------------------------------
igw-hub-${environment}-${region}:
  name: igw-hub-${environment}-${region}
  vpc_name: vpc-hub-${environment}-${region}