---
#-----------------------------------
# Demo
#-----------------------------------
demo:
  name: demo
  comment: AWS RDS PostgreSQL Catalog
  connection_name: rds-hub-postgresql-${environment}-${region}
  isolation_mode: ISOLATED
  options:
    database: demo