---
#-----------------------------------
# Eastus
#-----------------------------------
metastore-${location}:
  force_destroy: true
  name: metastore-${location}
  owner: null
  region: ${location}
  storage_account_name: null
  storage_container_name: null
