---
#-----------------------------------
# Workload
#-----------------------------------
workload:
  group_names: 
    - global-admins
  permissions:
    - ADMIN
  workspace_name: adb-workload-${environment}-${region}