---
#-----------------------------------
# Hub - Endpoints
#-----------------------------------
allow-aws-inbound:
  access: Allow
  destination_address_prefix: '*'
  destination_port_range: '*'
  direction: Inbound
  name: allow-aws-inbound
  network_security_group_name: sg-hub-endpoints-${environment}-${location}
  priority: 200
  protocol: Tcp
  resource_group_name: rg-hub-${environment}-${location}
  source_address_prefix: 192.168.0.0/16
  source_port_range: '*'

