---
#-----------------------------------
# Hub
#-----------------------------------
vnet-hub-${environment}-${location}:
  address_space:
    - 192.168.0.0/16
  dns_servers: null
  name: vnet-hub-${environment}-${location}
  resource_group_name: rg-hub-${environment}-${location}