---
#-----------------------------------
# Endpoints
#-----------------------------------
sgr-hub-endpoints-${environment}-${region}:
  description: Security group for VPC endpoints
  name: sgr-hub-endpoints-${environment}-${region}
  vpc_name: vpc-hub-${environment}-${region}
#-----------------------------------
# Public
#-----------------------------------
sgr-hub-public-${environment}-${region}:
  description: Security group for public instances
  name: sgr-hub-public-${environment}-${region}
  vpc_name: vpc-hub-${environment}-${region}
#-----------------------------------
# RDS
#-----------------------------------
sgr-hub-rds-${environment}-${region}:
  description: Security group for RDS instances
  name: sgr-hub-rds-${environment}-${region}
  vpc_name: vpc-hub-${environment}-${region}
#-----------------------------------
# ALB
#-----------------------------------
sgr-hub-alb-${environment}-${region}:
  description: Security group for ALB instances
  name: sgr-hub-alb-${environment}-${region}
  vpc_name: vpc-hub-${environment}-${region}
